name: i_exp
dependencies:
  - python>=3.6
  - flake8
  - pylint
  - black
  - mypy
  - pip
  - pip:
    - git+https://github.com/JakeColtman/bartpy.git
  - ipython
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - geopandas
  - scikit-learn